

NGraphics = {
	COUNTRY_FLAG_TEX_WIDTH = 82, -- Expected texture size
	COUNTRY_FLAG_TEX_HEIGHT = 52,
	COUNTRY_FLAG_MEDIUM_TEX_WIDTH = 41,
	COUNTRY_FLAG_MEDIUM_TEX_HEIGHT = 26,
	COUNTRY_FLAG_SMALL_TEX_WIDTH = 10,
	COUNTRY_FLAG_SMALL_TEX_HEIGHT = 7,
	COUNTRY_FLAG_TEX_MAX_SIZE = 2048,
	COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 2048,
	COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10,
	COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 8196,
	COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41,
	COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 16384,
	VICTORY_POINT_LEVELS = 2,
	VICTORY_POINT_MAP_ICON_AFTER = {0, 20}, -- After this amount of VP the map icon becomes bigger dot.
	VICTORY_POINT_MAP_ICON_TEXT_CUTOFF =  {350, 450, 750},  -- At what camera distance the VP name text disappears.
	VICTORY_POINTS_DISTANCE_CUTOFF = {350, 700, 1400},  -- At what distance VPs are hidden
	CAPITAL_ICON_CUTOFF = 1400,	-- At what camera distance capital icons disappears
	UNITS_DISTANCE_CUTOFF = 200,
}

for k,v in pairs( NDefines_Graphics ) do NDefines[k] = v end
